language: node_js
node_js: stable
dist: trusty
addons:
  firefox: latest
  chrome: stable
cache:
  directories:
  - node_modules
  - bower_components
before_script:
- npm install -g bower polylint web-component-tester
- bower install
- polylint
script:
- xvfb-run wct
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct --plugin sauce --skip-plugin
  local; fi
